---
- name: Deploy Application with Docker
  hosts: dev
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:

    - name: Remove old Docker container if exists
      command: docker rm -f web
      ignore_errors: yes

    - name: Remove old Docker image if exists
      command: docker rmi -f nisargaraj/webapp:latest
      ignore_errors: yes

    - name: Log in to Docker Hub
      command: echo "Nisarga@992" | docker login -u nisargaraj --password-stdin

    - name: Pull Docker Image from Docker Hub
      command: docker pull nisargaraj/webapp:latest

    - name: Run Docker Container
      command: docker run -it -d --name web -p 8081:8080 nisargaraj/webapp:latest